### ISSUE TITLE
fastqc and Apple

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#276] opened 2022-01-02 05:19 UTC
I am putting this here so that more people know about it.

There was an issue brought up in the Cecret github issues (https://github.com/UPHL-BioNGS/Cecret/issues/88) that there may be an issue with the fastqc container and docker on some Apple products.

> Is this related to the Apple M1 chip I am using? I've attempted to use Option 1 and Option 2 to run from Docker and Singularity and I encounter an issue with the StaphB FastQC Docker container:
>
> FATAL: Unable to pull docker://staphb/fastqc:latest: conveyor failed to get: no descriptor found for reference "5d67fad373325a597d0eb75d0986ad7dd78f8b2b67e78435d9176c434a8cec04"
>
> Is this an issue with the Apple M1 chips?

If this is an issue with the Apple M1 chips, we may want to include sort of disclaimer.

**Comment by jrichardsz** [comment] 2022-01-02 16:29
Is the issue related to build a Dockerfile on a mac or build a Dockerfile with app dependencies on a linux machine?

**Comment by MillironX** [comment] 2022-01-03 13:21
This issue isn't specific for Mac/M1: I have gotten this error multiple times on a mix of local and Slurm HPC nodes. It's mainly related to the way Nextflow interacts with the `singularity pull` command. See:

- https://github.com/nextflow-io/nextflow/issues/1210
- https://github.com/apptainer/singularity/issues/4555

Anecdotally, I've found the issue is less prevalent on Singularity 3.8.x vs. earlier releases, but I don't have any numbers to back that, and there might be other factors involved.

Also anecdotally, I've had better success specifying the domain for all images, e.g. `docker.io/staphb/fastqc:latest` rather than just `staphb/fastqc:latest`.

In any case, this can usually be resolved by running `singularity pull docker://staphb/fastqc:latest` (or whatever container name is giving trouble) prior to executing the Nextflow pipeline. Singularity will then pick up on the cached image and transfer it to Nextflow.

**Closed** 2022-01-21 16:48 UTC
Labels: wontfix
